package org.cargobroker.context;

public enum DataKeys {
    API_RESPONSE,
    LATEST_ORDER_ID,
    BID_AMOUNT,
    BID_CURRENCY,
    BID_COMMENT,
    CLIENT_ORGANIZATION,
    CLIENT_SPOKESPERSON,
    CLIENT_EMAIL,
    CLIENT_ADDRESS,
    CLIENT_PHONE,
    PAGE_LOGIN,
    PAGE_ORDERS,
    PAGE_ORDER_CREATION,
    PAGE_CLIENTS,
    PAGE_CLIENT_CREATION,
    TEST_RUN_TIME,
    TEST_CURRENT
}
